services:
  app:
    build: .
    container_name: social-network-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=social_network
      - DB_SSLMODE=disable
      - API_PORT=5000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - social-network

  db:
    image: postgres:15-alpine
    container_name: social-network-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - social-network

volumes:
  postgres_data:

networks:
  social-network:
    driver: bridge